;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Buildable.Ceiling",DevComment="")
+GameplayTagList=(Tag="Buildable.Ceiling.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Ceiling.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Ceiling.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Door",DevComment="")
+GameplayTagList=(Tag="Buildable.Door.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Door.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Door.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Foundation.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Foundation.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Foundation.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Door",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Door.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Door.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Door.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Standard",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Standard.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Standard.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Standard.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Window",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Window.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Window.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Window.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Window",DevComment="")
+GameplayTagList=(Tag="Buildable.Window.Metal",DevComment="")
+GameplayTagList=(Tag="Buildable.Window.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Window.Wood",DevComment="")
+GameplayTagList=(Tag="Event.OpenDoor",DevComment="")
+GameplayTagList=(Tag="Event.OpenWindow",DevComment="")

